In [6]:
import os
import sys
sys.path.append('../')

from library import Graph, GraphLib

In [7]:
graphLib = GraphLib(config='./config_test.yaml')
print(graphLib)

Graph Library with configurations:
{'dataset': 'CIFAR10', 'classes': 10, 'input_channels': 3, 'image_size': 28, 'data_dir': '/scratch/gpfs/stuli/pytorch_datasets/', 'manual_dir': None, 'train_batch_size': 256, 'test_batch_size': 512, 'module_vertices': 4, 'head_vertices': 4, 'max_edges': 9, 'max_modules': 2, 'base_ops': ['conv5x5-bn-relu', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'maxpool3x3'], 'default_channels': 128, 'default_stride': 1, 'flatten_ops': ['global-avg-pool', 'flatten'], 'dense_ops': ['dense-1024', 'dense-4096', 'dropout-p5', 'dropout-p4'], 'hash_algo': 'sha256'}
Number of graphs: 0


In [8]:
graphLib.build_library()

Generating modules...
Using 4 vertices, 4 labels, max 9 edges
	Generated up to 3 vertices: 8 modules (8 without hashing)
	Generated up to 4 vertices: 156 modules (168 without hashing)

Generating heads...
Using 4 vertices, 6 labels
	Generated up to 4 vertices: 2 heads (2 without hashing)

Generating graphs...
Using max 2 modules



	Generated up to 1 modules: 312 graphs



	Generated up to 2 modules: 48824 graphs
Graph library created! 
48824 graphs within the design space.


In [9]:
graphLib.save_dataset('./dataset.json')

Dataset saved to: ./dataset.json


In [10]:
graphLib_new = GraphLib.load_from_dataset('./dataset.json')
graphLib_new

Graph Library with configurations:
{'dataset': 'CIFAR10', 'classes': 10, 'input_channels': 3, 'image_size': 28, 'data_dir': '/scratch/gpfs/stuli/pytorch_datasets/', 'manual_dir': None, 'train_batch_size': 256, 'test_batch_size': 512, 'module_vertices': 4, 'head_vertices': 4, 'max_edges': 9, 'max_modules': 2, 'base_ops': ['conv5x5-bn-relu', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'maxpool3x3'], 'default_channels': 128, 'default_stride': 1, 'flatten_ops': ['global-avg-pool', 'flatten'], 'dense_ops': ['dense-1024', 'dense-4096', 'dropout-p5', 'dropout-p4'], 'hash_algo': 'sha256'}
Number of graphs: 48824

In [11]:
import sys
sys.path.append('../')

from library import Graph, GraphLib

graphLib = GraphLib.load_from_dataset('./dataset.json')

graphLib.library[-5]

Model parameters: None
Accuracies: {'train': None, 'val': None, 'test': None}
Embedding: None
Hash: b6f597c07898c3f16289177fefd5c08ff2ca8cea4df6650145a977616c69f241
Module:
[[0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]
Labels:['input', 'maxpool3x3', 'maxpool3x3', 'output']
Module:
[[0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]
Labels:['input', 'maxpool3x3', 'conv3x3-bn-relu', 'output']
Module:
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
Labels:['input', 'flatten', 'dense_classes', 'output']

In [4]:
import sys
sys.path.append('../')

from library import Graph, GraphLib

from model_builder import CNNBenchModel

graphLib = GraphLib.load_from_dataset('./dataset.json')

model = CNNBenchModel(graphLib.config, graphLib.library[-1])
print(model)

CNNBenchModel(
  (op_m0_v1): MaxPool2d(kernel_size=(3, 3), stride=1, padding=0, dilation=1, ceil_mode=False)
  (proj_m0_v1): Conv2d(3, 3, kernel_size=(1, 1), stride=(1, 1))
  (op_m0_v2): MaxPool2d(kernel_size=(3, 3), stride=1, padding=0, dilation=1, ceil_mode=False)
  (proj_m0_v2): Conv2d(3, 3, kernel_size=(1, 1), stride=(1, 1))
  (proj_m0): Conv2d(3, 6, kernel_size=(1, 1), stride=(1, 1))
  (op_m1_v1): MaxPool2d(kernel_size=(3, 3), stride=1, padding=0, dilation=1, ceil_mode=False)
  (proj_m1_v1): Conv2d(6, 6, kernel_size=(1, 1), stride=(1, 1))
  (op_m1_v2): MaxPool2d(kernel_size=(3, 3), stride=1, padding=0, dilation=1, ceil_mode=False)
  (proj_m1_v2): Conv2d(6, 6, kernel_size=(1, 1), stride=(1, 1))
  (proj_m1): Conv2d(6, 12, kernel_size=(1, 1), stride=(1, 1))
  (op_m2_v2): Linear(in_features=6912, out_features=10, bias=True)
)


In [5]:
import torch

inp = torch.rand(64, 3, 28, 28)

logits = model(inp)

print(logits[0, :])

tensor([ 1.5093, -1.3635, -1.8411,  1.1338, -0.3166, -0.4797, -0.2892,  1.6679,
         1.2841,  0.9083], grad_fn=<SliceBackward>)
