In [1]:
import json
import os
import re
import tensorflow as tf
import copy
import numpy as np
import random
import sys

if '../' not in sys.path:
    sys.path.append('../')
    
from cnnbench.lib import config as _config

# Set DEBUG to True to print intermediate variables
DEBUG = False

# Define model directory
model_dir = '../results/vertices_3/'

In [ ]:
config = _config.build_config()
dataset = None

with open(os.path.join(model_dir, 'generated_graphs.json')) as f:
    models = json.load(f)

if DEBUG: print(f'All hashes: models.keys()')    


In [2]:
loaded_dataset = tf.data.TFRecordDataset(os.path.join(model_dir, 'cnnbench.tfrecord'))

features = {
        'module_adjacency': tf.io.FixedLenSequenceFeature([], tf.int64, allow_missing=True),
        'module_operations': tf.io.FixedLenFeature([], tf.string),
        'trainable_parameters': tf.io.FixedLenFeature([], tf.int64),
        'training_time': tf.io.FixedLenFeature([], tf.float32),
        'train_accuracy': tf.io.FixedLenFeature([], tf.float32),
        'validation_accuracy': tf.io.FixedLenFeature([], tf.float32),
        'test_accuracy': tf.io.FixedLenFeature([], tf.float32)}

def _parse_image_function(example_proto):
  return tf.io.parse_single_example(example_proto, features)

parsed_dataset = loaded_dataset.map(_parse_image_function)
parsed_dataset
for elem in parsed_dataset:
    raw_adjacency = elem['module_adjacency'].numpy()
    dim = int(np.sqrt(len(raw_adjacency)))
    adjacency = np.array([int(e) for e in list(raw_adjacency)], dtype=np.int8)
    adjacency = np.reshape(adjacency, (dim, dim))
    
    operations = elem['module_operations'].numpy().decode("utf-8")
    trainable_parameters = elem['trainable_parameters'].numpy()
    training_time = elem['training_time'].numpy()
    train_accuracy = elem['train_accuracy'].numpy()
    validation_accuracy = elem['validation_accuracy'].numpy()
    test_accuracy = elem['test_accuracy'].numpy()
    print(f'Adjacency matrix: \n{adjacency} \nOperations: {operations} \nTrainable parameters: {trainable_parameters}')
    print(f'Train Accuracy: {train_accuracy} \nValidation Accuracy: {validation_accuracy} \nTest Accuracy: {test_accuracy}\n')

Adjacency matrix: 
[[0 1]
 [0 0]] 
Operations: input,output 
Trainable parameters: 882570
Train Accuracy: 0.1982366144657135 
Validation Accuracy: 0.19716282188892365 
Test Accuracy: 0.1994190663099289

Adjacency matrix: 
[[0 1]
 [0 0]] 
Operations: input,output 
Trainable parameters: 882570
Train Accuracy: 0.0998883917927742 
Validation Accuracy: 0.09930098801851273 
Test Accuracy: 0.09985977411270142

Adjacency matrix: 
[[0 1]
 [0 0]] 
Operations: input,output 
Trainable parameters: 882570
Train Accuracy: 0.20361606776714325 
Validation Accuracy: 0.21073190867900848 
Test Accuracy: 0.20042067766189575

Adjacency matrix: 
[[0 1 1]
 [0 0 1]
 [0 0 0]] 
Operations: input,conv3x3-bn-relu,output 
Trainable parameters: 11051402
Train Accuracy: 0.10022321343421936 
Validation Accuracy: 0.09950657933950424 
Test Accuracy: 0.10006009787321091

Adjacency matrix: 
[[0 1 1]
 [0 0 1]
 [0 0 0]] 
Operations: input,conv3x3-bn-relu,output 
Trainable parameters: 11051402
Train Accuracy: 0.1003348231315